CREATE TABLE `backtesting_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`model_id` int NOT NULL,
	`stock_symbol` varchar(10) NOT NULL,
	`start_date` timestamp NOT NULL,
	`end_date` timestamp NOT NULL,
	`total_days` int NOT NULL,
	`total_return` int NOT NULL,
	`annualized_return` int NOT NULL,
	`sharpe_ratio` int NOT NULL,
	`sortino_ratio` int NOT NULL,
	`max_drawdown` int NOT NULL,
	`total_trades` int NOT NULL,
	`winning_trades` int NOT NULL,
	`losing_trades` int NOT NULL,
	`win_rate` int NOT NULL,
	`avg_win` int NOT NULL,
	`avg_loss` int NOT NULL,
	`profit_factor` int NOT NULL,
	`value_at_risk_95` int NOT NULL,
	`conditional_var_95` int NOT NULL,
	`test_type` enum('in_sample','out_of_sample','walk_forward') NOT NULL,
	`trade_log` text,
	`equity_curve` text,
	`tested_at` timestamp NOT NULL DEFAULT (now()),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `backtesting_results_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `dark_pool_activity` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stock_symbol` varchar(10) NOT NULL,
	`trade_date` timestamp NOT NULL,
	`trade_time` varchar(20) NOT NULL,
	`volume` int NOT NULL,
	`price` int NOT NULL,
	`total_value` int NOT NULL,
	`trade_type` enum('block','sweep','split','unusual') NOT NULL,
	`sentiment` enum('bullish','bearish','neutral') NOT NULL,
	`percent_of_daily_volume` int NOT NULL,
	`price_vs_vwap` int,
	`significance` enum('low','medium','high','extreme') NOT NULL DEFAULT 'medium',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `dark_pool_activity_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `intraday_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stock_symbol` varchar(10) NOT NULL,
	`trading_date` timestamp NOT NULL,
	`pre_market_open` int,
	`pre_market_high` int,
	`pre_market_low` int,
	`pre_market_close` int,
	`pre_market_volume` int,
	`pre_market_change` int,
	`regular_open` int NOT NULL,
	`regular_high` int NOT NULL,
	`regular_low` int NOT NULL,
	`regular_close` int NOT NULL,
	`regular_volume` int NOT NULL,
	`post_market_open` int,
	`post_market_high` int,
	`post_market_low` int,
	`post_market_close` int,
	`post_market_volume` int,
	`post_market_change` int,
	`gap_type` enum('gap_up','gap_down','no_gap'),
	`gap_size` int,
	`gap_pct` int,
	`gap_filled` enum('yes','no','partial'),
	`vwap` int NOT NULL,
	`vwap_deviation` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `intraday_data_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `market_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stock_symbol` varchar(10),
	`event_type` enum('earnings','dividend','split','fed_meeting','economic_data','conference','ipo','merger','other') NOT NULL,
	`event_date` timestamp NOT NULL,
	`event_time` varchar(20),
	`title` varchar(255) NOT NULL,
	`description` text,
	`importance` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium',
	`estimated_eps` int,
	`actual_eps` int,
	`eps_surprise` int,
	`dividend_amount` int,
	`ex_dividend_date` timestamp,
	`payment_date` timestamp,
	`split_ratio` varchar(20),
	`price_impact` int,
	`volume_impact` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `market_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `news_sentiment_cache` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stock_symbol` varchar(10) NOT NULL,
	`title` text NOT NULL,
	`source` varchar(255) NOT NULL,
	`url` text,
	`published_at` timestamp NOT NULL,
	`sentiment_score` int NOT NULL,
	`sentiment_label` enum('bearish','neutral','bullish') NOT NULL,
	`relevance_score` int NOT NULL,
	`summary` text,
	`topics` text,
	`cached_at` timestamp NOT NULL DEFAULT (now()),
	`expires_at` timestamp NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `news_sentiment_cache_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `options_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stock_symbol` varchar(10) NOT NULL,
	`option_type` enum('call','put') NOT NULL,
	`strike_price` int NOT NULL,
	`expiration_date` timestamp NOT NULL,
	`last_price` int NOT NULL,
	`bid` int NOT NULL,
	`ask` int NOT NULL,
	`volume` int NOT NULL,
	`open_interest` int NOT NULL,
	`volume_oi_ratio` int NOT NULL,
	`delta` int NOT NULL,
	`gamma` int NOT NULL,
	`theta` int NOT NULL,
	`vega` int NOT NULL,
	`rho` int NOT NULL,
	`implied_volatility` int NOT NULL,
	`iv_percentile` int,
	`iv_rank` int,
	`pre_earnings_iv` int,
	`post_earnings_iv` int,
	`iv_crush_pct` int,
	`data_timestamp` timestamp NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `options_data_id` PRIMARY KEY(`id`)
);
