CREATE TABLE `institutional_options_analysis` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stock_symbol` varchar(10) NOT NULL,
	`option_type` enum('call','put') NOT NULL,
	`strike_price` int NOT NULL,
	`expiration_date` timestamp NOT NULL,
	`days_to_expiry` int NOT NULL,
	`last_price` int NOT NULL,
	`bid` int NOT NULL,
	`ask` int NOT NULL,
	`mid_price` int NOT NULL,
	`current_stock_price` int NOT NULL,
	`final_score` int NOT NULL,
	`rating` enum('EXCEPTIONAL','EXCELLENT','GOOD','ACCEPTABLE','NEUTRAL') NOT NULL,
	`volatility_score` int NOT NULL,
	`greeks_score` int NOT NULL,
	`technical_score` int NOT NULL,
	`liquidity_score` int NOT NULL,
	`event_risk_score` int NOT NULL,
	`sentiment_score` int NOT NULL,
	`flow_score` int NOT NULL,
	`expected_value_score` int NOT NULL,
	`delta` int NOT NULL,
	`gamma` int NOT NULL,
	`vega` int NOT NULL,
	`theta` int NOT NULL,
	`implied_volatility` int NOT NULL,
	`spread_pct` int NOT NULL,
	`volume` int NOT NULL,
	`open_interest` int NOT NULL,
	`kelly_pct` int NOT NULL,
	`conservative_kelly` int NOT NULL,
	`max_position_size_pct` int NOT NULL,
	`historical_volatility` int,
	`days_to_earnings` int,
	`insights` text,
	`analysis_timestamp` timestamp NOT NULL,
	`engine_version` varchar(20) NOT NULL,
	`actual_outcome` enum('profit','loss','breakeven','pending') DEFAULT 'pending',
	`actual_return` int,
	`days_held` int,
	`exit_price` int,
	`exit_date` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `institutional_options_analysis_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `options_analysis_scan` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stock_symbol` varchar(10) NOT NULL,
	`total_options_analyzed` int NOT NULL,
	`calls_analyzed` int NOT NULL,
	`puts_analyzed` int NOT NULL,
	`calls_passed_filters` int NOT NULL,
	`puts_passed_filters` int NOT NULL,
	`calls_above_threshold` int NOT NULL,
	`puts_above_threshold` int NOT NULL,
	`top_call_score` int,
	`top_put_score` int,
	`stock_price` int NOT NULL,
	`market_volatility` int,
	`scan_timestamp` timestamp NOT NULL,
	`scan_duration_ms` int NOT NULL,
	`engine_version` varchar(20) NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `options_analysis_scan_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `trained_models` ADD `model_data` mediumtext;